parameters:
#    story_story.example.class: Story\StoryBundle\Example

services:
#    story_story.example:
#        class: %story_story.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
