Story\StoryBundle\Entity\Story:
    type: entity
    table: story
    indexes:
        p_id:
            columns:
                - p_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        line:
            type: string
            nullable: false
            length: 140
            fixed: false
            comment: ''
    manyToOne:
        p:
            targetEntity: Story
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                p_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
